### ISSUE TITLE
Import Error running qcluster command Python 3.7 Django 2.1.5

### ISSUE THREAD

**Issue by viperfx** [Koed00/django-q#331]
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "ENV/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "ENV/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "ENV/lib/python3.7/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "ENV/lib/python3.7/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "ENV/versions/3.7.0/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "ENV/lib/python3.7/site-packages/django_q/management/commands/qcluster.py", line 4, in <module>
    from django_q.cluster import Cluster
  File "ENV/lib/python3.7/site-packages/django_q/cluster.py", line 24, in <module>
    from django_q import tasks
  File "ENV/lib/python3.7/site-packages/django_q/tasks.py", line 12, in <module>
    from django_q.cluster import worker, monitor
ImportError: cannot import name 'worker' from 'django_q.cluster' (ENV/lib/python3.7/site-packages/django_q/cluster.py)
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

**Comment by Koed00** [comment]
Can't reproduce this. Works fine on  Python 3.7.2 with Django 2.1.5.

**Comment by theunraveler** [comment]
Looks to me like a circular import:

```
File "{ENV}/lib/python3.6/site-packages/django_q/cluster.py", line 24, in <module>
    from django_q import tasks
  File "{ENV}/lib/python3.6/site-packages/django_q/tasks.py", line 12, in <module>
    from django_q.cluster import worker, monitor
```

**Comment by Koed00** [comment]
@viperfx could it have been that you were running Django 1.11?

**Comment by theunraveler** [comment]
Is this a known issue on Django 1.11?

**Comment by codeSamuraii** [comment]
I'm running into this issue as well...
> Django 2.1.7 - Django-q 1.0.1

**Comment by Yungbubu** [comment]
+1 

Django-q 1.0.1
Django 2.1.4
Python 3.6.0

**Comment by codeSamuraii** [comment]
I have a temporary fix.

In `django_q/tasks.py`, replace the line : 
```
from django_q.cluster import worker, monitor
```
by
```
from django_q.cluster import *
```

The `manage.py qcluster` command works for me.

**Comment by telenieko** [comment]
Same with Django 2.1.7, django-q 1.0.1, python 3.6.8
Same with Django 2.1.5, django-q 1.0.1, python 3.6.8
Same with Django 2.1.0, django-q 1.0.1, python 3.6.8
Same with Django 2.1.0, django-q 1.0.0, python 3.6.8

**Comment by sato-s** [comment]
I have same issue.

Python 3.7.2,Django              2.1.5,django-q            1.0.1

**Comment by viperfx** [comment]
@Koed00 I think it's worth reviewing this? 

Seems to be a long list of people having this issue?

**Comment by lamby** [comment]
Can reproduce here:

 * `django.VERSION == (2, 2, 0, 'final', 0)`
 * `django-q` version `1.0.1`
 * `sys.version` is `3.7.2+ (default, Feb  2 2019, 14:31:48) \n[GCC 8.2.0]`

**Comment by lamby** [comment]
Alternative PR created at https://github.com/Koed00/django-q/pull/356

**Comment by grigory51** [comment]
Put your `django_q` app in INSTALLED_APPS after `django.contrib.admin`

**Comment by lamby** [comment]
I'm not using `django.contrib.admin` and am seeing this.

**Comment by joantune** [comment]
Guys! - had the same issue with Python 3.7.0 - and Django 2.1.7

Solved it - the issue was that I didn't have `django.contrib.admin` in the `INSTALLED_APPS` - just make sure it's there and before `django_q`
Cheers!

**Comment by lamby** [comment]
Perhaps, but that's not the real, ongoing solution. I mean, `django-q` should not require using the Django admin, at the very least, and the order of `INSTALLED_APPS` should not make any difference.
